FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y postgresql-server-dev-all
RUN apt-get install -y python3-dev
RUN apt-get install -y python3-pip
RUN pip3 install uwsgi
ADD /requirements.txt /app/
WORKDIR /app
RUN pip3 install -r requirements.txt
CMD uwsgi --http :8080 --wsgi-file backend.py --callable app
